# Generated by Django 6.0.2 on 2026-03-15 21:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-ZА-Я][a-zA-Zа-яА-Я\\s-]*$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-ZА-Я][a-zA-Zа-яА-Я\\s-]*$')], verbose_name='Last Name'),
        ),
    ]
