# Generated by Django 6.0.1 on 2026-03-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_member_membership_start_alter_member_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Member Photo'),
        ),
    ]
