# Generated by Django 6.0.2 on 2026-02-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
