
\restrict EGU4QKz9oKCTNIsoorFd0GdzbV9Gfx1WMcqV4QpzBPNa5AdYvGBKX2lFzk6gwlt

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;


ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;


ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;


ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE public.courses_course (
    id bigint NOT NULL,
    title character varying(100) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    language character varying(32) NOT NULL,
    level character varying(10) NOT NULL
);


ALTER TABLE public.courses_course OWNER TO postgres;


ALTER TABLE public.courses_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.courses_lesson (
    id bigint NOT NULL,
    title character varying(150) NOT NULL,
    content text NOT NULL,
    "order" integer NOT NULL,
    course_id bigint NOT NULL,
    duration_minutes smallint NOT NULL,
    learning_objective character varying(255) NOT NULL,
    image_url character varying(200) NOT NULL,
    CONSTRAINT courses_lesson_duration_minutes_check CHECK ((duration_minutes >= 0)),
    CONSTRAINT courses_lesson_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.courses_lesson OWNER TO postgres;



ALTER TABLE public.courses_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.courses_progress (
    id bigint NOT NULL,
    score integer NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.courses_progress OWNER TO postgres;






ALTER TABLE public.courses_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.courses_question (
    id bigint NOT NULL,
    external_id character varying(100) NOT NULL,
    text text NOT NULL,
    option_a character varying(200) NOT NULL,
    option_b character varying(200) NOT NULL,
    option_c character varying(200) NOT NULL,
    option_d character varying(200) NOT NULL,
    correct_option character varying(1) NOT NULL,
    hint text NOT NULL,
    quiz_id bigint NOT NULL
);


ALTER TABLE public.courses_question OWNER TO postgres;






ALTER TABLE public.courses_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.courses_quiz (
    id bigint NOT NULL,
    title character varying(150) NOT NULL,
    lesson_id bigint NOT NULL,
    image_url character varying(200) NOT NULL
);


ALTER TABLE public.courses_quiz OWNER TO postgres;






ALTER TABLE public.courses_quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;






ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;






ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;






ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;






CREATE TABLE public.users_aichatmessage (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    language character varying(5) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    session_id bigint
);


ALTER TABLE public.users_aichatmessage OWNER TO postgres;






ALTER TABLE public.users_aichatmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_aichatmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.users_aichatsession (
    id bigint NOT NULL,
    title character varying(180) NOT NULL,
    language character varying(5) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_aichatsession OWNER TO postgres;






ALTER TABLE public.users_aichatsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_aichatsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(15),
    telegram_chat_id character varying(50),
    account_role character varying(20) NOT NULL,
    study_streak integer NOT NULL,
    last_study_date date,
    xp_points integer NOT NULL,
    profile_image character varying(100),
    CONSTRAINT users_customuser_study_streak_check CHECK ((study_streak >= 0)),
    CONSTRAINT users_customuser_xp_points_check CHECK ((xp_points >= 0))
);


ALTER TABLE public.users_customuser OWNER TO postgres;






CREATE TABLE public.users_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_customuser_groups OWNER TO postgres;






ALTER TABLE public.users_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







CREATE TABLE public.users_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_customuser_user_permissions OWNER TO postgres;






ALTER TABLE public.users_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);







ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);







ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);







ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);







ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.courses_lesson
    ADD CONSTRAINT courses_lesson_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.courses_progress
    ADD CONSTRAINT courses_progress_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.courses_question
    ADD CONSTRAINT courses_question_external_id_key UNIQUE (external_id);







ALTER TABLE ONLY public.courses_question
    ADD CONSTRAINT courses_question_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.courses_quiz
    ADD CONSTRAINT courses_quiz_lesson_id_key UNIQUE (lesson_id);







ALTER TABLE ONLY public.courses_quiz
    ADD CONSTRAINT courses_quiz_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);







ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);







ALTER TABLE ONLY public.users_aichatmessage
    ADD CONSTRAINT users_aichatmessage_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.users_aichatsession
    ADD CONSTRAINT users_aichatsession_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_email_key UNIQUE (email);







ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (customuser_id, group_id);







ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (customuser_id, permission_id);







ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id);







ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_username_key UNIQUE (username);







CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);







CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);







CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);







CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);







CREATE INDEX courses_lesson_course_id_16bc4882 ON public.courses_lesson USING btree (course_id);







CREATE INDEX courses_progress_course_id_394d582b ON public.courses_progress USING btree (course_id);







CREATE INDEX courses_progress_lesson_id_90725fed ON public.courses_progress USING btree (lesson_id);







CREATE INDEX courses_progress_user_id_05563a38 ON public.courses_progress USING btree (user_id);







CREATE INDEX courses_question_external_id_56010243_like ON public.courses_question USING btree (external_id varchar_pattern_ops);







CREATE INDEX courses_question_quiz_id_7bd87b34 ON public.courses_question USING btree (quiz_id);







CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);







CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);







CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);







CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);







CREATE INDEX users_aichatmessage_session_id_7eb0cb13 ON public.users_aichatmessage USING btree (session_id);







CREATE INDEX users_aichatmessage_user_id_280baff3 ON public.users_aichatmessage USING btree (user_id);







CREATE INDEX users_aichatsession_user_id_ace94397 ON public.users_aichatsession USING btree (user_id);







CREATE INDEX users_customuser_email_6445acef_like ON public.users_customuser USING btree (email varchar_pattern_ops);







CREATE INDEX users_customuser_groups_customuser_id_958147bf ON public.users_customuser_groups USING btree (customuser_id);







CREATE INDEX users_customuser_groups_group_id_01390b14 ON public.users_customuser_groups USING btree (group_id);







CREATE INDEX users_customuser_user_permissions_customuser_id_5771478b ON public.users_customuser_user_permissions USING btree (customuser_id);







CREATE INDEX users_customuser_user_permissions_permission_id_baaa2f74 ON public.users_customuser_user_permissions USING btree (permission_id);







CREATE INDEX users_customuser_username_80452fdf_like ON public.users_customuser USING btree (username varchar_pattern_ops);







ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.courses_lesson
    ADD CONSTRAINT courses_lesson_course_id_16bc4882_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.courses_progress
    ADD CONSTRAINT courses_progress_course_id_394d582b_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.courses_progress
    ADD CONSTRAINT courses_progress_lesson_id_90725fed_fk_courses_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.courses_progress
    ADD CONSTRAINT courses_progress_user_id_05563a38_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.courses_question
    ADD CONSTRAINT courses_question_quiz_id_7bd87b34_fk_courses_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.courses_quiz(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.courses_quiz
    ADD CONSTRAINT courses_quiz_lesson_id_2bf49392_fk_courses_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.users_aichatmessage
    ADD CONSTRAINT users_aichatmessage_session_id_7eb0cb13_fk_users_aic FOREIGN KEY (session_id) REFERENCES public.users_aichatsession(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.users_aichatmessage
    ADD CONSTRAINT users_aichatmessage_user_id_280baff3_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.users_aichatsession
    ADD CONSTRAINT users_aichatsession_user_id_ace94397_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_gro_customuser_id_958147bf_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_customuser_id_5771478b_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;







ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;








\unrestrict EGU4QKz9oKCTNIsoorFd0GdzbV9Gfx1WMcqV4QpzBPNa5AdYvGBKX2lFzk6gwlt

