# Generated by Django 6.0.2 on 2026-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
