# Generated by Django 6.0.2 on 2026-02-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treats', '0002_kiosk_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiosk',
            name='ice_cream_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treats.ice_cream'),
        ),
    ]
