# Generated by Django 6.0.2 on 2026-03-03 12:50

import WebPA413.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название курса')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка курса')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название группы')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^[A-ZА-Я][a-zа-я-]*$')], verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-ZА-Я][a-zа-я-]*$')], verbose_name='Имя')),
                ('iin', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^[0-9]*$'), WebPA413.models.CheckIIN], verbose_name='ИИН')),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPA413.group')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Assestment')),
                ('date', models.DateTimeField(verbose_name='Exam Date')),
                ('fee', models.FloatField(default=0, verbose_name='The exam fee')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPA413.course', verbose_name='Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPA413.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
