# Generated by Django 6.0.2 on 2026-03-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Brend Name')),
                ('country', models.CharField(max_length=100, verbose_name="Brand's Country")),
                ('info', models.TextField(blank=True, null=True, verbose_name='Brend info')),
                ('big_logo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Logo of The Brand')),
                ('small_logo', models.BinaryField(verbose_name='Brand author')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='FIO Client')),
                ('iin', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='IIN Client')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Clients Photo')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Goods Name')),
                ('count', models.PositiveIntegerField(verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='The Goods Price')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info about the good')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Photo of the picture')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.brand', verbose_name='Brand Owners ')),
            ],
            options={
                'verbose_name': 'Good',
                'verbose_name_plural': 'Goods',
                'managed': True,
                'unique_together': {('name', 'id_brand')},
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True, verbose_name='The time of the beginning of the buying')),
                ('pay_date', models.DateField(auto_now=True, verbose_name='The time of the tiem to pay')),
                ('count', models.PositiveBigIntegerField(verbose_name='Amount')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Common Price')),
                ('is_pay', models.BooleanField(default=False, verbose_name='Bill fact')),
                ('id_customer', models.ManyToManyField(related_name='Goods', to='ShopApp.customer')),
                ('id_goods', models.ManyToManyField(related_name='Customer', to='ShopApp.goods')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'managed': True,
            },
        ),
    ]
