# Generated by Django 6.0.2 on 2026-03-13 15:17

import Members.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Branch Name')),
                ('address', models.CharField(max_length=255, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Gym Branch',
                'verbose_name_plural': 'Gym Branches',
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plan Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration_months', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-ZА-Я][a-zа-я-]*$')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-ZА-Я][a-zа-я-]*$')], verbose_name='Last Name')),
                ('iin', models.CharField(max_length=12, unique=True, validators=[Members.models.CheckIIN], verbose_name='IIN')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.gymbranch', verbose_name='Home Branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Members.membershipplan', verbose_name='Current Plan')),
            ],
        ),
    ]
