# Generated by Django 6.0.2 on 2026-02-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='The City Name')),
                ('info', models.TextField(verbose_name='Information about the city')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='The Street Name')),
                ('info', models.TextField(verbose_name='Information of the street')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample1.cities', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='House Number')),
                ('id_street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample1.street')),
            ],
        ),
    ]
