# Generated by Django 6.0.2 on 2026-02-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sample1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Houses',
            new_name='House',
        ),
    ]
