# Generated by Django 6.0.2 on 2026-02-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sample1', '0002_rename_houses_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'managed': True, 'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'managed': True, 'verbose_name': 'Street', 'verbose_name_plural': 'Streets'},
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('id_street', 'number')},
        ),
    ]
